service: notifier

# Example commands using the serverless secrets plugin:
# serverless decrypt --stage dev --password '<serverless_password>'
# serverless encrypt --stage dev --password '<serverless_password>'
# serverless deploy --stage dev
# serverless deploy --stage dev

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs6.10

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  notifications:
    handler: handler.notifications
    environment:
      EMAIL: ${self:custom.secrets.EMAIL}
      EMAIL_PASSWORD: ${self:custom.secrets.EMAIL_PASSWORD}
    events:
      - http:
          path: notifications/send
          method: post