service: notification

# Example commands using the serverless secrets plugin:
# serverless decrypt --stage dev --password '<serverless_password>'
# serverless encrypt --stage dev --password '<serverless_password>'
# serverless deploy --stage dev

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  apiKeys:
      - ${self:custom.secrets.API_KEY}
  usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  runtime: nodejs6.10

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  notifications:
    handler: handler.notifications
    environment:
      EMAIL: ${self:custom.secrets.EMAIL}
      EMAIL_PASSWORD: ${self:custom.secrets.EMAIL_PASSWORD}
    events:
      - http:
          path: notifications/send
          method: post
          private: true